Remove error.cause.
As far as I can tell, it was never being set properly, but
was being accessed by some of the error views, causing:

!! Unexpected error while processing request: undefined method `cause' for #<Deltacloud::ExceptionHandler::ProviderError:0x7f422b038558>
undefined method `cause' for #<Deltacloud::ExceptionHandler::ProviderError:0x7f422b038558>

Just remove it until someone needs to use it.

Signed-off-by: Chris Lalancette <clalance@redhat.com>

git-svn-id: https://svn.apache.org/repos/asf/incubator/deltacloud/trunk@1133377 13f79535-47bb-0310-9956-ffa450edef68