Client: don't require lib/base_object
client/lib/deltacloud.rb was recently changed to require 'lib/base_object'
rather than 'base_object' which results in:

  $ irb -rubygems
  irb(main):001:0> require 'deltacloud'
  LoadError: no such file to load -- lib/base_object
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/gems/1.8/gems/deltacloud-client-0.4.0/lib/deltacloud.rb:26
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:59:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:59:in `require'
    from (irb):1

When you load a gem, 'lib' is automatically included in the load path.

git-svn-id: https://svn.apache.org/repos/asf/incubator/deltacloud/trunk@1159107 13f79535-47bb-0310-9956-ffa450edef68